[package]
name = "incpa-recursing"
version.workspace = true
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
derive-new.workspace = true
incpa-ioe.workspace = true
incpa-state.workspace = true
